### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by 2mac** [TodorBalabanov/Scribe4#2]
Please include a license file and copyright declaration. Optionally, place a license header in the source files.

**Comment by TodorBalabanov** [comment]
Thanks for this feedback, but license is a little bit problematic. I have cloned the project from this one: https://github.com/MatrixFrog/scribedroid There is no license file and I am not confident how to deal with your request. Most of the code is written by Tyler Breisacher and I do not know what is his idea for license. I will ask him.

**Comment by TodorBalabanov** [comment]
It is solved.
